DROP DATABASE IF EXISTS oraculum;
CREATE DATABASE oraculum;
USE oraculum;

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    correo VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(50) DEFAULT 'user',
    puntuacion INT DEFAULT 0
);

CREATE TABLE categoria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE pregunta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    enunciado VARCHAR(300) NOT NULL UNIQUE,
    dificultad VARCHAR(50) NOT NULL,
    pista TEXT,
    explicacion TEXT,
    id_categoria INT,
    FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

CREATE TABLE respuesta (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texto TEXT NOT NULL,
    es_correcta BOOLEAN DEFAULT false,
    id_pregunta INT,
    FOREIGN KEY (id_pregunta) REFERENCES pregunta(id) ON DELETE CASCADE
);

CREATE TABLE partida (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_usuario INT,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    puntuacion INT,
    modo_juego VARCHAR(50) NOT NULL,  -- 'aventura', 'prueba', 'contrarreloj', 'infinito'
    id_categoria INT,
    dificultad VARCHAR(50) NOT NULL,  -- 'heroica', 'divina'
    FOREIGN KEY (id_usuario) REFERENCES usuario(id),
    FOREIGN KEY (id_categoria) REFERENCES categoria(id)
);

CREATE TABLE datos_partida (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_partida INT,
    id_pregunta INT,
    id_respuesta_elegida INT,
    id_respuesta_correcta INT,
    tiempo_respuesta INT,
    uso_pista BOOLEAN DEFAULT FALSE,
    puntuacion_pregunta INT,
    FOREIGN KEY (id_partida) REFERENCES partida(id),
    FOREIGN KEY (id_pregunta) REFERENCES pregunta(id),
    FOREIGN KEY (id_respuesta_elegida) REFERENCES respuesta(id),
    FOREIGN KEY (id_respuesta_correcta) REFERENCES respuesta(id)
);

-- No se insertan usuarios de prueba debido al hasheo de las contraseñas

-- Insertar categorías
INSERT INTO categoria (nombre) VALUES
('Mitología griega'),
('Superhéroes');

-- Insertar preguntas y respuestas

-- 🔵 Mitología griega

-- Preguntas nivel medio
INSERT INTO pregunta (enunciado, dificultad, pista, explicacion, id_categoria) VALUES
('¿Quién es el rey de los dioses griegos?', 'heroica', 'Controla los rayos y truenos.', 'Zeus es el dios supremo del Olimpo.', 1),
('¿Cómo se llama el dios del mar?', 'heroica', 'Hermano de Zeus.', 'Poseidón gobierna los océanos y mares.', 1),
('¿Quién es la diosa de la sabiduría?', 'heroica', 'Nació de la cabeza de Zeus.', 'Atenea es la diosa de la sabiduría y la guerra estratégica.', 1),
('¿Qué héroe mató al Minotauro?', 'heroica', 'Usó un hilo para no perderse.', 'Teseo derrotó al Minotauro en el laberinto de Creta.', 1),
('¿Quién abrió la caja que liberó todos los males?', 'heroica', 'Primera mujer creada por los dioses.', 'Pandora abrió la caja por curiosidad.', 1),
('¿Cómo se llama el caballo alado?', 'heroica', 'Nació de la sangre de Medusa.', 'Pegaso es el famoso caballo con alas.', 1),
('¿Quién robó el fuego para dárselo a los humanos?', 'heroica', 'Fue castigado por Zeus.', 'Prometeo desafió a los dioses para ayudar a la humanidad.', 1),
('¿Cómo se llama el perro de tres cabezas?', 'heroica', 'Guarda la entrada del inframundo.', 'Cerbero vigila las puertas del Hades.', 1),
('¿Quién es la diosa del amor y la belleza?', 'heroica', 'Nació de la espuma del mar.', 'Afrodita es la diosa del amor.', 1),
('¿Qué titán sostiene el mundo?', 'heroica', 'Su nombre se usa para mapas.', 'Atlas fue condenado a cargar el cielo.', 1),
('¿Quién completó los doce trabajos?', 'heroica', 'Famoso por su fuerza sobrehumana.', 'Heracles realizó doce trabajos como penitencia.', 1),
('¿Cómo se llama el dios de la guerra?', 'heroica', 'Hijo de Zeus y Hera.', 'Ares es el dios griego de la guerra.', 1),
('¿Quién es el mensajero de los dioses?', 'heroica', 'Lleva sandalias aladas.', 'Hermes es el mensajero divino.', 1),
('¿Cómo se llama la diosa de la caza?', 'heroica', 'Hermana gemela de Apolo.', 'Artemisa es la diosa cazadora.', 1),
('¿Quién castigó a Sísifo?', 'heroica', 'Rey del inframundo.', 'Hades impuso el castigo eterno a Sísifo.', 1),
('¿Qué monstruo convertía en piedra con la mirada?', 'heroica', 'Tenía serpientes por cabello.', 'Medusa petrificaba a quien la mirara.', 1),
('¿Quién mató a Medusa?', 'heroica', 'Usó un escudo como espejo.', 'Perseo decapitó a Medusa.', 1),
('¿Cómo se llama el dios del sol?', 'heroica', 'Hermano de Artemisa.', 'Apolo es el dios de la luz y la música.', 1),
('¿Quién es la esposa de Zeus?', 'heroica', 'Diosa del matrimonio.', 'Hera es la reina del Olimpo.', 1),
('¿Qué criatura tenía cuerpo de león y cabeza humana?', 'heroica', 'Hacía acertijos mortales.', 'La Esfinge aterrorizaba Tebas con sus enigmas.', 1),
('¿Quién es el dios del inframundo?', 'heroica', 'Hermano de Zeus y Poseidón.', 'Hades gobierna el reino de los muertos.', 1),
('¿Cómo se llama la diosa de la agricultura?', 'heroica', 'Madre de Perséfone.', 'Deméter controla las cosechas.', 1),
('¿Qué héroe navegó durante diez años para volver a casa?', 'heroica', 'Rey de Ítaca.', 'Odiseo protagonizó la Odisea.', 1),
('¿Quién era invulnerable excepto en el talón?', 'heroica', 'Héroe de la guerra de Troya.', 'Aquiles tenía un punto débil en el talón.', 1),
('¿Cómo se llama el monte donde viven los dioses?', 'heroica', 'La montaña más alta de Grecia.', 'El monte Olimpo es el hogar divino.', 1),
('¿Quién construyó el laberinto de Creta?', 'heroica', 'Famoso inventor y arquitecto.', 'Dédalo diseñó el laberinto del Minotauro.', 1),
('¿Qué le pasó a Ícaro?', 'heroica', 'Voló demasiado cerca del sol.', 'Ícaro se precipitó al mar cuando se derritió la cera.', 1),
('¿Quién es el dios del vino?', 'heroica', 'También llamado Baco.', 'Dioniso es el dios de la vid y la celebración.', 1),
('¿Cómo se llama la mujer más bella del mundo?', 'heroica', 'Su rapto causó la guerra de Troya.', 'Helena de Troya era famosa por su belleza.', 1),
('¿Quién tocaba la lira tan bien que calmaba a las fieras?', 'heroica', 'Bajó al inframundo por amor.', 'Orfeo era un músico legendario.', 1),
('¿Qué guerreras amazonas lucharon contra los griegos?', 'heroica', 'Sociedad de mujeres guerreras.', 'Las Amazonas eran temibles luchadoras.', 1),
('¿Quién era el centauro más sabio?', 'heroica', 'Maestro de muchos héroes.', 'Quirón educó a grandes héroes griegos.', 1),
('¿Cómo se llama el río que separa el mundo de los muertos?', 'heroica', 'Hay que pagar al barquero.', 'El río Estigia divide el mundo de los vivos y muertos.', 1),
('¿Quién es el barquero del inframundo?', 'heroica', 'Transporta almas al otro lado.', 'Caronte lleva las almas por el río Estigia.', 1),
('¿Qué criatura tenía múltiples cabezas que regeneraban?', 'heroica', 'Heracles la derrotó.', 'La Hidra de Lerna regeneraba sus cabezas.', 1),
('¿Quién era el rey de Troya?', 'heroica', 'Padre de Héctor y Paris.', 'Príamo gobernaba Troya durante la guerra.', 1),
('¿Cómo se llama el héroe troyano más valiente?', 'heroica', 'Hermano de Paris.', 'Héctor defendió Troya valientemente.', 1),
('¿Quién raptó a Helena?', 'heroica', 'Príncipe troyano.', 'Paris causó la guerra al raptar a Helena.', 1),
('¿Qué estratagema usaron los griegos para entrar en Troya?', 'heroica', 'Un regalo de madera.', 'El caballo de Troya fue una trampa genial.', 1),
('¿Quién ideó el caballo de Troya?', 'heroica', 'Rey de Ítaca, muy astuto.', 'Odiseo planeó la estratagema del caballo.', 1),
('¿Cómo se llama la diosa de la discordia?', 'heroica', 'Causó problemas en una boda.', 'Eris provocó el juicio de Paris.', 1),
('¿Qué fruta causó el juicio de Paris?', 'heroica', 'Fruto dorado de la discordia.', 'La manzana de oro inició la disputa entre diosas.', 1),
('¿Quién forjaba las armas de los dioses?', 'heroica', 'Dios cojo del fuego.', 'Hefesto era el herrero divino.', 1),
('¿Cómo se llama la ninfa que se enamoró de su reflejo?', 'heroica', 'Se convirtió en flor.', 'Narciso se enamoró de su propia imagen.', 1),
('¿Quién era la musa de la épica?', 'heroica', 'Inspiraba grandes poemas.', 'Calíope era la musa de la poesía épica.', 1),
('¿Quién era el padre de Zeus?', 'heroica', 'Titán que devoraba a sus hijos.', 'Cronos temía ser destronado por sus descendientes.', 1),
('¿Cómo se llama la diosa del hogar?', 'heroica', 'Hermana de Zeus, muy pacífica.', 'Hestia protegía el fuego sagrado del hogar.', 1),
('¿Qué criatura tenía cabeza de toro y cuerpo de hombre?', 'heroica', 'Vivía en un laberinto en Creta.', 'El Minotauro era hijo de Pasífae y un toro.', 1),
('¿Quién era la madre de Perséfone?', 'heroica', 'Diosa de las cosechas.', 'Deméter buscó desesperadamente a su hija raptada.', 1),
('¿Cómo se llama el dios de los sueños?', 'heroica', 'Hijo de Hipnos, el sueño.', 'Morfeo enviaba sueños a los mortales.', 1);

-- Respuestas nivel medio
INSERT INTO respuesta (texto, es_correcta, id_pregunta) VALUES
('Zeus', TRUE, 1), ('Poseidón', FALSE, 1), ('Hades', FALSE, 1), ('Apolo', FALSE, 1),
('Poseidón', TRUE, 2), ('Zeus', FALSE, 2), ('Hades', FALSE, 2), ('Ares', FALSE, 2),
('Atenea', TRUE, 3), ('Hera', FALSE, 3), ('Afrodita', FALSE, 3), ('Artemisa', FALSE, 3),
('Teseo', TRUE, 4), ('Heracles', FALSE, 4), ('Perseo', FALSE, 4), ('Aquiles', FALSE, 4),
('Pandora', TRUE, 5), ('Helena', FALSE, 5), ('Casandra', FALSE, 5), ('Penélope', FALSE, 5),
('Pegaso', TRUE, 6), ('Centauro', FALSE, 6), ('Hipogrifo', FALSE, 6), ('Unicornio', FALSE, 6),
('Prometeo', TRUE, 7), ('Epimeteo', FALSE, 7), ('Atlas', FALSE, 7), ('Cronos', FALSE, 7),
('Cerbero', TRUE, 8), ('Hidra', FALSE, 8), ('Quimera', FALSE, 8), ('Esfinge', FALSE, 8),
('Afrodita', TRUE, 9), ('Hera', FALSE, 9), ('Atenea', FALSE, 9), ('Deméter', FALSE, 9),
('Atlas', TRUE, 10), ('Cronos', FALSE, 10), ('Prometeo', FALSE, 10), ('Epimeteo', FALSE, 10),
('Heracles', TRUE, 11), ('Teseo', FALSE, 11), ('Perseo', FALSE, 11), ('Aquiles', FALSE, 11),
('Ares', TRUE, 12), ('Zeus', FALSE, 12), ('Apolo', FALSE, 12), ('Hermes', FALSE, 12),
('Hermes', TRUE, 13), ('Apolo', FALSE, 13), ('Ares', FALSE, 13), ('Hefesto', FALSE, 13),
('Artemisa', TRUE, 14), ('Atenea', FALSE, 14), ('Hera', FALSE, 14), ('Afrodita', FALSE, 14),
('Hades', TRUE, 15), ('Zeus', FALSE, 15), ('Poseidón', FALSE, 15), ('Ares', FALSE, 15),
('Medusa', TRUE, 16), ('Esfinge', FALSE, 16), ('Quimera', FALSE, 16), ('Hidra', FALSE, 16),
('Perseo', TRUE, 17), ('Heracles', FALSE, 17), ('Teseo', FALSE, 17), ('Aquiles', FALSE, 17),
('Apolo', TRUE, 18), ('Helios', FALSE, 18), ('Zeus', FALSE, 18), ('Hermes', FALSE, 18),
('Hera', TRUE, 19), ('Atenea', FALSE, 19), ('Afrodita', FALSE, 19), ('Deméter', FALSE, 19),
('Esfinge', TRUE, 20), ('Medusa', FALSE, 20), ('Quimera', FALSE, 20), ('Hidra', FALSE, 20),
('Hades', TRUE, 21), ('Zeus', FALSE, 21), ('Poseidón', FALSE, 21), ('Ares', FALSE, 21),
('Deméter', TRUE, 22), ('Hera', FALSE, 22), ('Atenea', FALSE, 22), ('Artemisa', FALSE, 22),
('Odiseo', TRUE, 23), ('Aquiles', FALSE, 23), ('Héctor', FALSE, 23), ('Paris', FALSE, 23),
('Aquiles', TRUE, 24), ('Heracles', FALSE, 24), ('Teseo', FALSE, 24), ('Perseo', FALSE, 24),
('Olimpo', TRUE, 25), ('Parnaso', FALSE, 25), ('Helicón', FALSE, 25), ('Etna', FALSE, 25),
('Dédalo', TRUE, 26), ('Hefesto', FALSE, 26), ('Prometeo', FALSE, 26), ('Atlas', FALSE, 26),
('Ícaro', TRUE, 27), ('Dédalo', FALSE, 27), ('Hermes', FALSE, 27), ('Pegaso', FALSE, 27),
('Dioniso', TRUE, 28), ('Apolo', FALSE, 28), ('Hermes', FALSE, 28), ('Ares', FALSE, 28),
('Helena', TRUE, 29), ('Afrodita', FALSE, 29), ('Hera', FALSE, 29), ('Casandra', FALSE, 29),
('Orfeo', TRUE, 30), ('Apolo', FALSE, 30), ('Hermes', FALSE, 30), ('Dioniso', FALSE, 30),
('Amazonas', TRUE, 31), ('Valkirias', FALSE, 31), ('Ninfas', FALSE, 31), ('Musas', FALSE, 31),
('Quirón', TRUE, 32), ('Neso', FALSE, 32), ('Folo', FALSE, 32), ('Euritión', FALSE, 32),
('Estigia', TRUE, 33), ('Leteo', FALSE, 33), ('Aqueronte', FALSE, 33), ('Cocito', FALSE, 33),
('Caronte', TRUE, 34), ('Hades', FALSE, 34), ('Tánato', FALSE, 34), ('Minos', FALSE, 34),
('Hidra', TRUE, 35), ('Cerbero', FALSE, 35), ('Quimera', FALSE, 35), ('Esfinge', FALSE, 35),
('Príamo', TRUE, 36), ('Héctor', FALSE, 36), ('Paris', FALSE, 36), ('Agamenón', FALSE, 36),
('Héctor', TRUE, 37), ('Paris', FALSE, 37), ('Eneas', FALSE, 37), ('Príamo', FALSE, 37),
('Paris', TRUE, 38), ('Héctor', FALSE, 38), ('Eneas', FALSE, 38), ('Príamo', FALSE, 38),
('Caballo de Troya', TRUE, 39), ('Asedio', FALSE, 39), ('Traición', FALSE, 39), ('Soborno', FALSE, 39),
('Odiseo', TRUE, 40), ('Aquiles', FALSE, 40), ('Agamenón', FALSE, 40), ('Menelao', FALSE, 40),
('Eris', TRUE, 41), ('Hera', FALSE, 41), ('Atenea', FALSE, 41), ('Afrodita', FALSE, 41),
('Manzana', TRUE, 42), ('Pera', FALSE, 42), ('Uva', FALSE, 42), ('Granada', FALSE, 42),
('Hefesto', TRUE, 43), ('Ares', FALSE, 43), ('Apolo', FALSE, 43), ('Hermes', FALSE, 43),
('Narciso', TRUE, 44), ('Adonis', FALSE, 44), ('Endimión', FALSE, 44), ('Ganimedes', FALSE, 44),
('Calíope', TRUE, 45), ('Clío', FALSE, 45), ('Euterpe', FALSE, 45), ('Melpómene', FALSE, 45),
('Cronos', TRUE, 46), ('Zeus', FALSE, 46), ('Urano', FALSE, 46), ('Gea', FALSE, 46),
('Hestia', TRUE, 47), ('Hera', FALSE, 47), ('Deméter', FALSE, 47), ('Atenea', FALSE, 47),
('Minotauro', TRUE, 48), ('Centauro', FALSE, 48), ('Sátiro', FALSE, 48), ('Cíclope', FALSE, 48),
('Deméter', TRUE, 49), ('Hera', FALSE, 49), ('Atenea', FALSE, 49), ('Afrodita', FALSE, 49),
('Morfeo', TRUE, 50), ('Hipnos', FALSE, 50), ('Tánato', FALSE, 50), ('Oneiros', FALSE, 50);

-- Preguntas nivel difícil
INSERT INTO pregunta (enunciado, dificultad, pista, explicacion, id_categoria) VALUES
('¿Cuál era el nombre del primer rey de Atenas según la mitología?', 'divina', 'Nació de la tierra y fue medio serpiente.', 'Cécrope fue el primer rey mítico de Atenas, nacido de la tierra.', 1),
('¿Qué ninfa se transformó en laurel para escapar de Apolo?', 'divina', 'Su nombre se asocia con las coronas de victoria.', 'Dafne se convirtió en laurel, árbol sagrado de Apolo.', 1),
('¿Quién era la madre de las Musas?', 'divina', 'Titánide de la memoria.', 'Mnemósine, la personificación de la memoria, fue madre de las nueve Musas.', 1),
('¿Cómo se llamaba el gigante que intentó violar a Leto?', 'divina', 'Fue enviado al Tártaro por Zeus.', 'Ticio fue castigado eternamente por intentar agredir a la madre de Apolo y Artemisa.', 1),
('¿Qué rey fue transformado en lobo por Zeus?', 'divina', 'Sirvió carne humana a los dioses.', 'Licaón fue castigado por su impiedad y canibalismo.', 1),
('¿Cuál era el nombre del caballo de Poseidón?', 'divina', 'Significa "espuma del mar".', 'Escifio era uno de los caballos inmortales de Poseidón.', 1),
('¿Qué titán robó el néctar y la ambrosía?', 'divina', 'Hijo de Jápeto, hermano de Prometeo.', 'Epimeteo, el "que piensa después", cometió este robo.', 1),
('¿Quién era el padre de las Harpías?', 'divina', 'Dios del viento del oeste.', 'Céfiro engendró a las Harpías con la ninfa Podarge.', 1),
('¿Cómo se llamaba la primera esposa de Zeus?', 'divina', 'Titánide de la prudencia.', 'Metis fue devorada por Zeus para evitar la profecía.', 1),
('¿Qué héroe fundó la ciudad de Micenas?', 'divina', 'Hijo de Perseo y Andrómeda.', 'Perses fundó Micenas según algunas versiones del mito.', 1),
('¿Cuál era el nombre del perro de Orión?', 'divina', 'Se convirtió en constelación.', 'Sirio, el perro de Orión, brilla como la estrella más luminosa.', 1),
('¿Qué diosa nació de la espuma del mar mezclada con los genitales de Urano?', 'divina', 'Surgió cerca de Chipre.', 'Afrodita nació de esta manera según Hesíodo.', 1),
('¿Quién era el auriga del carro solar antes que Helios?', 'divina', 'Titán de la luz.', 'Hiperión conducía el carro solar en la era de los Titanes.', 1),
('¿Cómo se llamaba la nodriza de Zeus en Creta?', 'divina', 'Cabra divina que lo amamantó.', 'Amaltea cuidó al joven Zeus en una cueva del monte Ida.', 1),
('¿Qué rey de Frigia convirtió todo en oro?', 'divina', 'Recibió este don de Dioniso.', 'Midas aprendió que la riqueza no lo es todo.', 1),
('¿Cuál era el nombre del río de fuego en el inframundo?', 'divina', 'Uno de los cinco ríos infernales.', 'Piriflegetonte era el río ardiente del Hades.', 1),
('¿Qué ninfa se enamoró de Narciso y se consumió de amor?', 'divina', 'Solo podía repetir las últimas palabras.', 'Eco fue castigada por Hera y se desvaneció por amor no correspondido.', 1),
('¿Quién era el padre de los Cíclopes?', 'divina', 'Primordial del cielo.', 'Urano engendró a los Cíclopes con Gea.', 1),
('¿Cómo se llamaba el gigante que sostenía las columnas del cielo?', 'divina', 'Hermano de Prometeo.', 'Atlas fue condenado a esta tarea tras la Titanomaquia.', 1),
('¿Qué diosa presidía los juramentos?', 'divina', 'Hija de la Noche.', 'Estigia personificaba los juramentos sagrados e inquebrantables.', 1),
('¿Quién era el heraldo de Hades?', 'divina', 'Dios de la muerte no violenta.', 'Tánato servía como mensajero del señor del inframundo.', 1),
('¿Cómo se llamaba la madre de Perséfone?', 'divina', 'Diosa de las cosechas y la agricultura.', 'Deméter buscó desesperadamente a su hija raptada.', 1),
('¿Qué rey de Corinto fue condenado a empujar una roca eternamente?', 'divina', 'Engañó a la muerte dos veces.', 'Sísifo fue castigado por su astucia excesiva.', 1),
('¿Quién era la diosa de la venganza?', 'divina', 'También llamada Adrastea.', 'Némesis castigaba la hybris y el orgullo desmedido.', 1),
('¿Cómo se llamaba el hijo de Dédalo?', 'divina', 'Voló demasiado alto con alas de cera.', 'Ícaro ignoró las advertencias de su padre.', 1),
('¿Qué titánide era la madre de Helios?', 'divina', 'Personificación de la vista.', 'Teia dio a luz al dios del sol.', 1),
('¿Quién era el dios de los vientos del norte?', 'divina', 'El más violento de los Anemoi.', 'Bóreas traía el frío invernal desde Tracia.', 1),
('¿Cómo se llamaba la esposa de Hefesto?', 'divina', 'Una de las Cárites.', 'Aglae era la más joven de las tres Gracias.', 1),
('¿Qué héroe mató a la Quimera?', 'divina', 'Montaba a Pegaso.', 'Belerofonte derrotó al monstruo desde el aire.', 1),
('¿Quién era el rey de los Lapitas?', 'divina', 'Luchó contra los Centauros en su boda.', 'Piritoo fue amigo de Teseo y enemigo de los Centauros.', 1),
('¿Cómo se llamaba la nave de Jasón?', 'divina', 'Construida con madera del bosque sagrado.', 'Argo llevó a los Argonautas en busca del Vellocino de Oro.', 1),
('¿Qué diosa ayudó a Jasón a conseguir el Vellocino?', 'divina', 'Hechicera de la Cólquide.', 'Medea traicionó a su padre por amor a Jasón.', 1),
('¿Quién era el padre de Aquiles?', 'divina', 'Rey de los Mirmidones.', 'Peleo se casó con la nereida Tetis.', 1),
('¿Cómo se llamaba la madre de Aquiles?', 'divina', 'Nereida que lo sumergió en la Estigia.', 'Tetis intentó hacer inmortal a su hijo.', 1),
('¿Qué profeta ciego advirtió a Edipo?', 'divina', 'Vivió siete generaciones.', 'Tiresias reveló terribles verdades sobre el destino.', 1),
('¿Quién era el rey de Tebas cuando llegó Edipo?', 'divina', 'Fue asesinado en un cruce de caminos.', 'Layo murió a manos de su propio hijo sin saberlo.', 1),
('¿Cómo se llamaba la reina de las Amazonas?', 'divina', 'Poseía un cinturón mágico.', 'Hipólita fue derrotada por Heracles en su noveno trabajo.', 1),
('¿Qué gigante desafió a los dioses en la Gigantomaquia?', 'divina', 'Rey de los Gigantes.', 'Porfirión intentó violar a Hera durante la batalla.', 1),
('¿Quién era la diosa de la juventud?', 'divina', 'Escanciaba néctar en el Olimpo.', 'Hebe servía a los dioses antes que Ganimedes.', 1),
('¿Cómo se llamaba el caballo de Aquiles?', 'divina', 'Podía hablar y profetizar.', 'Janto predijo la muerte de su amo.', 1),
('¿Qué rey de Lidia podía convertir todo en oro?', 'divina', 'Aprendió que era una maldición.', 'Midas pidió a Dioniso que le quitara el don.', 1),
('¿Quién era la diosa de la discordia?', 'divina', 'Causó la guerra de Troya.', 'Eris arrojó la manzana dorada en la boda de Peleo y Tetis.', 1),
('¿Cómo se llamaba el barquero del río Aqueronte?', 'divina', 'Transportaba almas al inframundo.', 'Caronte exigía un óbolo por el viaje.', 1),
('¿Qué titán enseñó la astronomía a los humanos?', 'divina', 'Padre de Prometeo.', 'Jápeto transmitió conocimientos celestiales.', 1),
('¿Quién era la diosa de la magia?', 'divina', 'Asociada con los cruces de caminos.', 'Hécate tenía poder sobre la tierra, mar y cielo.', 1),
('¿Cómo se llamaba el hijo de Poseidón que fue cegado por Odiseo?', 'divina', 'Cíclope pastor de ovejas.', 'Polifemo fue engañado por la astucia de Odiseo.', 1),
('¿Qué diosa transformó a Aracne en araña?', 'divina', 'Diosa de la sabiduría y las artes.', 'Atenea castigó la arrogancia de la tejedora mortal.', 1),
('¿Quién era el dios de los rebaños y pastores?', 'divina', 'Tenía cuernos y patas de cabra.', 'Pan causaba el "pánico" con su grito.', 1),
('¿Cómo se llamaba la esposa de Orfeo?', 'divina', 'Murió por la mordedura de una serpiente.', 'Eurídice fue perdida dos veces por Orfeo.', 1),
('¿Qué rey fue castigado a tener hambre y sed eternas?', 'divina', 'Sirvió a su hijo como comida a los dioses.', 'Tántalo dio nombre al suplicio del tantalismo.', 1);

-- Respuestas nivel difícil
INSERT INTO respuesta (texto, es_correcta, id_pregunta) VALUES
('Cécrope', TRUE, 51), ('Erecteo', FALSE, 51), ('Teseo', FALSE, 51), ('Egeo', FALSE, 51),
('Dafne', TRUE, 52), ('Siringa', FALSE, 52), ('Eco', FALSE, 52), ('Clitia', FALSE, 52),
('Mnemósine', TRUE, 53), ('Temis', FALSE, 53), ('Rea', FALSE, 53), ('Tetis', FALSE, 53),
('Ticio', TRUE, 54), ('Ixión', FALSE, 54), ('Sísifo', FALSE, 54), ('Tántalo', FALSE, 54),
('Licaón', TRUE, 55), ('Penteo', FALSE, 55), ('Acteón', FALSE, 55), ('Orfeo', FALSE, 55),
('Escifio', TRUE, 56), ('Arión', FALSE, 56), ('Pegaso', FALSE, 56), ('Janto', FALSE, 56),
('Epimeteo', TRUE, 57), ('Prometeo', FALSE, 57), ('Atlas', FALSE, 57), ('Menecio', FALSE, 57),
('Céfiro', TRUE, 58), ('Bóreas', FALSE, 58), ('Noto', FALSE, 58), ('Euro', FALSE, 58),
('Metis', TRUE, 59), ('Temis', FALSE, 59), ('Hera', FALSE, 59), ('Leto', FALSE, 59),
('Perses', TRUE, 60), ('Alceo', FALSE, 60), ('Esténelo', FALSE, 60), ('Electrión', FALSE, 60),
('Sirio', TRUE, 61), ('Lélape', FALSE, 61), ('Argos', FALSE, 61), ('Ortro', FALSE, 61),
('Afrodita', TRUE, 62), ('Atenea', FALSE, 62), ('Hera', FALSE, 62), ('Artemisa', FALSE, 62),
('Hiperión', TRUE, 63), ('Helios', FALSE, 63), ('Apolo', FALSE, 63), ('Febo', FALSE, 63),
('Amaltea', TRUE, 64), ('Ida', FALSE, 64), ('Adrastea', FALSE, 64), ('Melissa', FALSE, 64),
('Midas', TRUE, 65), ('Creso', FALSE, 65), ('Giges', FALSE, 65), ('Candaules', FALSE, 65),
('Piriflegetonte', TRUE, 66), ('Cocito', FALSE, 66), ('Aqueronte', FALSE, 66), ('Leteo', FALSE, 66),
('Eco', TRUE, 67), ('Siringa', FALSE, 67), ('Dafne', FALSE, 67), ('Clitia', FALSE, 67),
('Urano', TRUE, 68), ('Cronos', FALSE, 68), ('Zeus', FALSE, 68), ('Poseidón', FALSE, 68),
('Atlas', TRUE, 69), ('Prometeo', FALSE, 69), ('Epimeteo', FALSE, 69), ('Menecio', FALSE, 69),
('Estigia', TRUE, 70), ('Temis', FALSE, 70), ('Némesis', FALSE, 70), ('Dice', FALSE, 70),
('Tánato', TRUE, 71), ('Hermes', FALSE, 71), ('Iris', FALSE, 71), ('Morfeo', FALSE, 71),
('Deméter', TRUE, 72), ('Rea', FALSE, 72), ('Hera', FALSE, 72), ('Cibeles', FALSE, 72),
('Sísifo', TRUE, 73), ('Tántalo', FALSE, 73), ('Ixión', FALSE, 73), ('Ticio', FALSE, 73),
('Némesis', TRUE, 74), ('Eris', FALSE, 74), ('Ate', FALSE, 74), ('Enio', FALSE, 74),
('Ícaro', TRUE, 75), ('Talos', FALSE, 75), ('Perdix', FALSE, 75), ('Catreo', FALSE, 75),
('Teia', TRUE, 76), ('Febe', FALSE, 76), ('Temis', FALSE, 76), ('Mnemósine', FALSE, 76),
('Bóreas', TRUE, 77), ('Céfiro', FALSE, 77), ('Noto', FALSE, 77), ('Euro', FALSE, 77),
('Aglae', TRUE, 78), ('Afrodita', FALSE, 78), ('Talía', FALSE, 78), ('Eufrósine', FALSE, 78),
('Belerofonte', TRUE, 79), ('Perseo', FALSE, 79), ('Heracles', FALSE, 79), ('Teseo', FALSE, 79),
('Piritoo', TRUE, 80), ('Teseo', FALSE, 80), ('Céneo', FALSE, 80), ('Caeneus', FALSE, 80),
('Argo', TRUE, 81), ('Beagle', FALSE, 81), ('Calipso', FALSE, 81), ('Sirena', FALSE, 81),
('Medea', TRUE, 82), ('Circe', FALSE, 82), ('Hécate', FALSE, 82), ('Pasífae', FALSE, 82),
('Peleo', TRUE, 83), ('Eaco', FALSE, 83), ('Telamón', FALSE, 83), ('Menecio', FALSE, 83),
('Tetis', TRUE, 84), ('Anfitrite', FALSE, 84), ('Galatea', FALSE, 84), ('Nereida', FALSE, 84),
('Tiresias', TRUE, 85), ('Calcas', FALSE, 85), ('Anfiarao', FALSE, 85), ('Melampo', FALSE, 85),
('Layo', TRUE, 86), ('Creonte', FALSE, 86), ('Eteocles', FALSE, 86), ('Polinices', FALSE, 86),
('Hipólita', TRUE, 87), ('Pentesilea', FALSE, 87), ('Antíope', FALSE, 87), ('Oritía', FALSE, 87),
('Porfirión', TRUE, 88), ('Alcioneo', FALSE, 88), ('Encélado', FALSE, 88), ('Tifón', FALSE, 88),
('Hebe', TRUE, 89), ('Iris', FALSE, 89), ('Ganimedes', FALSE, 89), ('Peito', FALSE, 89),
('Janto', TRUE, 90), ('Balio', FALSE, 90), ('Arión', FALSE, 90), ('Pegaso', FALSE, 90),
('Midas', TRUE, 91), ('Creso', FALSE, 91), ('Giges', FALSE, 91), ('Candaules', FALSE, 91),
('Eris', TRUE, 92), ('Némesis', FALSE, 92), ('Ate', FALSE, 92), ('Enio', FALSE, 92),
('Caronte', TRUE, 93), ('Radamantis', FALSE, 93), ('Minos', FALSE, 93), ('Eaco', FALSE, 93),
('Jápeto', TRUE, 94), ('Cronos', FALSE, 94), ('Océano', FALSE, 94), ('Ceo', FALSE, 94),
('Hécate', TRUE, 95), ('Circe', FALSE, 95), ('Medea', FALSE, 95), ('Pasífae', FALSE, 95),
('Polifemo', TRUE, 96), ('Brontes', FALSE, 96), ('Estéropes', FALSE, 96), ('Arges', FALSE, 96),
('Atenea', TRUE, 97), ('Hera', FALSE, 97), ('Afrodita', FALSE, 97), ('Artemisa', FALSE, 97),
('Pan', TRUE, 98), ('Silvano', FALSE, 98), ('Fauno', FALSE, 98), ('Príapo', FALSE, 98),
('Eurídice', TRUE, 99), ('Calíope', FALSE, 99), ('Clío', FALSE, 99), ('Euterpe', FALSE, 99),
('Tántalo', TRUE, 100), ('Sísifo', FALSE, 100), ('Ixión', FALSE, 100), ('Ticio', FALSE, 100);

-- 🟣 Superhéroes

-- Preguntas nivel medio
INSERT INTO pregunta (enunciado, dificultad, pista, explicacion, id_categoria) VALUES
('¿Cuál es el nombre real de Superman?', 'heroica', 'Reportero del Daily Planet.', 'Clark Kent es la identidad secreta de Superman.', 2),
('¿De qué planeta viene Superman?', 'heroica', 'Fue destruido antes de que naciera.', 'Krypton era el planeta natal de Superman.', 2),
('¿Cuál es la debilidad de Superman?', 'heroica', 'Mineral radioactivo de su planeta.', 'La kryptonita es mortal para Superman.', 2),
('¿Cómo se llama la ciudad donde vive Superman?', 'heroica', 'Ciudad ficticia donde trabaja como reportero.', 'Metrópolis es el hogar adoptivo de Superman.', 2),
('¿Cuál es el nombre real de Batman?', 'heroica', 'Millonario de Gotham City.', 'Bruce Wayne es la identidad secreta de Batman.', 2),
('¿Cómo se llama el mayordomo de Batman?', 'heroica', 'Fiel servidor de la familia Wayne.', 'Alfred Pennyworth cuida de Bruce Wayne.', 2),
('¿En qué ciudad opera Batman?', 'heroica', 'Ciudad oscura y corrupta.', 'Gotham City es el territorio de Batman.', 2),
('¿Cuál es el nombre real de Spider-Man?', 'heroica', 'Estudiante que fue mordido por una araña.', 'Peter Parker se convirtió en Spider-Man.', 2),
('¿Qué le dio poderes a Spider-Man?', 'heroica', 'Accidente en un laboratorio.', 'Una araña radioactiva mordió a Peter Parker.', 2),
('¿Cuál es el nombre real de Wonder Woman?', 'heroica', 'Princesa amazona.', 'Diana Prince es la identidad de Wonder Woman.', 2),
('¿De dónde viene Wonder Woman?', 'heroica', 'Isla habitada solo por mujeres guerreras.', 'Themyscira es el hogar de las amazonas.', 2),
('¿Cuál es el arma característica de Wonder Woman?', 'heroica', 'Cuerda mágica que obliga a decir la verdad.', 'El lazo de la verdad es su arma principal.', 2),
('¿Cuál es el nombre real de Flash?', 'heroica', 'Científico forense de Central City.', 'Barry Allen es la identidad de Flash.', 2),
('¿Cuál es el superpoder principal de Flash?', 'heroica', 'Puede correr más rápido que la luz.', 'La súper velocidad es el poder de Flash.', 2),
('¿Cuál es el nombre real de Green Lantern?', 'heroica', 'Piloto de pruebas.', 'Hal Jordan es uno de los Green Lantern más famosos.', 2),
('¿De dónde obtiene sus poderes Green Lantern?', 'heroica', 'Joya alienígena en su dedo.', 'El anillo de poder le da sus habilidades.', 2),
('¿Cuál es el nombre real de Aquaman?', 'heroica', 'Rey de los océanos.', 'Arthur Curry es la identidad de Aquaman.', 2),
('¿Dónde gobierna Aquaman?', 'heroica', 'Reino submarino.', 'Atlantis es el reino de Aquaman.', 2),
('¿Cuál es el nombre del archienemigo de Batman?', 'heroica', 'Payaso criminal loco.', 'El Joker es el némesis principal de Batman.', 2),
('¿Cómo se llama el archienemigo de Superman?', 'heroica', 'Genio criminal calvo.', 'Lex Luthor es el enemigo más conocido de Superman.', 2),
('¿Cuál es el nombre real de Iron Man?', 'heroica', 'Genio millonario inventor.', 'Tony Stark es la identidad de Iron Man.', 2),
('¿Qué alimenta el traje de Iron Man?', 'heroica', 'Reactor en su pecho.', 'El reactor arc mantiene vivo a Tony Stark.', 2),
('¿Cuál es el nombre real de Captain America?', 'heroica', 'Soldado de la Segunda Guerra Mundial.', 'Steve Rogers se convirtió en Captain America.', 2),
('¿Qué objeto característico usa Captain America?', 'heroica', 'Arma defensiva circular.', 'Su escudo de vibranium es indestructible.', 2),
('¿Cuál es el nombre real de Thor?', 'heroica', 'Dios nórdico del trueno.', 'Thor Odinson es su nombre completo.', 2),
('¿Cómo se llama el martillo de Thor?', 'heroica', 'Solo los dignos pueden levantarlo.', 'Mjolnir es el martillo encantado de Thor.', 2),
('¿Cuál es el nombre real de Hulk?', 'heroica', 'Científico expuesto a radiación gamma.', 'Bruce Banner se transforma en Hulk.', 2),
('¿Qué desencadena la transformación de Hulk?', 'heroica', 'Emoción intensa negativa.', 'La ira convierte a Banner en Hulk.', 2),
('¿Cuál es el nombre real de Black Widow?', 'heroica', 'Espía rusa entrenada desde niña.', 'Natasha Romanoff es Black Widow.', 2),
('¿Cuál es el nombre real de Hawkeye?', 'heroica', 'Arquero experto de S.H.I.E.L.D.', 'Clint Barton es la identidad de Hawkeye.', 2),
('¿Cómo se llama el grupo de superhéroes de Marvel?', 'heroica', 'Los héroes más poderosos de la Tierra.', 'Los Vengadores protegen el mundo.', 2),
('¿Cómo se llama el grupo de superhéroes de DC?', 'heroica', 'Liga de los héroes más importantes.', 'La Liga de la Justicia defiende la Tierra.', 2),
('¿Cuál es el nombre real de Wolverine?', 'heroica', 'Mutante con garras de adamantium.', 'Logan es el nombre de Wolverine.', 2),
('¿Cuál es el poder principal de Wolverine?', 'heroica', 'Puede curarse de cualquier herida.', 'El factor de curación regenera su cuerpo.', 2),
('¿Cuál es el nombre real de Cyclops?', 'heroica', 'Líder de los X-Men.', 'Scott Summers es la identidad de Cyclops.', 2),
('¿Cuál es el poder de Cyclops?', 'heroica', 'Rayos destructivos de sus ojos.', 'Los rayos ópticos son su habilidad mutante.', 2),
('¿Cuál es el nombre real de Storm?', 'heroica', 'Mutante que controla el clima.', 'Ororo Munroe es la identidad de Storm.', 2),
('¿Cuál es el poder de Storm?', 'heroica', 'Domina los fenómenos meteorológicos.', 'Puede controlar el tiempo atmosférico.', 2),
('¿Quién es el líder de los X-Men?', 'heroica', 'Profesor telepático en silla de ruedas.', 'Charles Xavier fundó la escuela para mutantes.', 2),
('¿Cuál es el nombre real del Profesor X?', 'heroica', 'Telepático más poderoso del mundo.', 'Charles Francis Xavier es su nombre completo.', 2),
('¿Cuál es el archienemigo de los X-Men?', 'heroica', 'Mutante que controla el magnetismo.', 'Magneto es el némesis principal de los X-Men.', 2),
('¿Cuál es el nombre real de Magneto?', 'heroica', 'Sobreviviente del Holocausto.', 'Erik Lehnsherr es la identidad de Magneto.', 2),
('¿Cuál es el nombre real de Deadpool?', 'heroica', 'Mercenario con factor de curación.', 'Wade Wilson se convirtió en Deadpool.', 2),
('¿Qué característica especial tiene Deadpool?', 'heroica', 'Habla directamente con el lector.', 'Rompe la cuarta pared constantemente.', 2),
('¿Cuál es el nombre real de Daredevil?', 'heroica', 'Abogado ciego de Hells Kitchen.', 'Matt Murdock es la identidad de Daredevil.', 2),
('¿Qué sentido perdió Daredevil?', 'heroica', 'Accidente químico en su infancia.', 'Perdió la vista pero ganó otros sentidos.', 2),
('¿Cuál es el nombre real de Punisher?', 'heroica', 'Ex-marine que busca venganza.', 'Frank Castle se convirtió en Punisher.', 2),
('¿Qué motivó a Punisher a convertirse en vigilante?', 'heroica', 'Tragedia familiar causada por criminales.', 'La muerte de su familia lo transformó.', 2),
('¿Cuál es el nombre real de Doctor Strange?', 'heroica', 'Cirujano que se convirtió en hechicero.', 'Stephen Strange es el Hechicero Supremo.', 2),
('¿Cuál es la especialidad de Doctor Strange?', 'heroica', 'Artes místicas y dimensiones alternativas.', 'Domina la magia y protege la realidad.', 2);

-- Respuestas nivel medio
INSERT INTO respuesta (texto, es_correcta, id_pregunta) VALUES
('Clark Kent', TRUE, 101), ('Bruce Wayne', FALSE, 101), ('Peter Parker', FALSE, 101), ('Tony Stark', FALSE, 101),
('Krypton', TRUE, 102), ('Marte', FALSE, 102), ('Venus', FALSE, 102), ('Saturno', FALSE, 102),
('Kryptonita', TRUE, 103), ('Magia', FALSE, 103), ('Fuego', FALSE, 103), ('Agua', FALSE, 103),
('Metrópolis', TRUE, 104), ('Gotham', FALSE, 104), ('Central City', FALSE, 104), ('Star City', FALSE, 104),
('Bruce Wayne', TRUE, 105), ('Clark Kent', FALSE, 105), ('Tony Stark', FALSE, 105), ('Steve Rogers', FALSE, 105),
('Alfred', TRUE, 106), ('Jarvis', FALSE, 106), ('Winston', FALSE, 106), ('Sebastian', FALSE, 106),
('Gotham City', TRUE, 107), ('Metrópolis', FALSE, 107), ('Central City', FALSE, 107), ('Coast City', FALSE, 107),
('Peter Parker', TRUE, 108), ('Miles Morales', FALSE, 108), ('Ben Reilly', FALSE, 108), ('Miguel Ohara', FALSE, 108),
('Araña radioactiva', TRUE, 109), ('Experimento químico', FALSE, 109), ('Rayo', FALSE, 109), ('Mutación', FALSE, 109),
('Diana Prince', TRUE, 110), ('Diana Trevor', FALSE, 110), ('Diana Kane', FALSE, 110), ('Diana Queen', FALSE, 110),
('Themyscira', TRUE, 111), ('Amazonas', FALSE, 111), ('Olimpo', FALSE, 111), ('Atlántida', FALSE, 111),
('Lazo de la verdad', TRUE, 112), ('Espada', FALSE, 112), ('Escudo', FALSE, 112), ('Brazaletes', FALSE, 112),
('Barry Allen', TRUE, 113), ('Wally West', FALSE, 113), ('Jay Garrick', FALSE, 113), ('Bart Allen', FALSE, 113),
('Súper velocidad', TRUE, 114), ('Fuerza', FALSE, 114), ('Vuelo', FALSE, 114), ('Invisibilidad', FALSE, 114),
('Hal Jordan', TRUE, 115), ('John Stewart', FALSE, 115), ('Guy Gardner', FALSE, 115), ('Kyle Rayner', FALSE, 115),
('Anillo de poder', TRUE, 116), ('Linterna', FALSE, 116), ('Batería', FALSE, 116), ('Cristal', FALSE, 116),
('Arthur Curry', TRUE, 117), ('Orin', FALSE, 117), ('Kaldur', FALSE, 117), ('Garth', FALSE, 117),
('Atlantis', TRUE, 118), ('Lemuria', FALSE, 118), ('Pacifica', FALSE, 118), ('Oceania', FALSE, 118),
('Joker', TRUE, 119), ('Pingüino', FALSE, 119), ('Riddler', FALSE, 119), ('Two-Face', FALSE, 119),
('Lex Luthor', TRUE, 120), ('Brainiac', FALSE, 120), ('Doomsday', FALSE, 120), ('Bizarro', FALSE, 120),
('Tony Stark', TRUE, 121), ('James Rhodes', FALSE, 121), ('Pepper Potts', FALSE, 121), ('Happy Hogan', FALSE, 121),
('Reactor arc', TRUE, 122), ('Energía solar', FALSE, 122), ('Batería', FALSE, 122), ('Combustible', FALSE, 122),
('Steve Rogers', TRUE, 123), ('Bucky Barnes', FALSE, 123), ('Sam Wilson', FALSE, 123), ('John Walker', FALSE, 123),
('Escudo', TRUE, 124), ('Martillo', FALSE, 124), ('Espada', FALSE, 124), ('Hacha', FALSE, 124),
('Thor Odinson', TRUE, 125), ('Loki Laufeyson', FALSE, 125), ('Balder', FALSE, 125), ('Heimdall', FALSE, 125),
('Mjolnir', TRUE, 126), ('Stormbreaker', FALSE, 126), ('Gungnir', FALSE, 126), ('Gram', FALSE, 126),
('Bruce Banner', TRUE, 127), ('Rick Jones', FALSE, 127), ('Betty Ross', FALSE, 127), ('Emil Blonsky', FALSE, 127),
('Ira', TRUE, 128), ('Miedo', FALSE, 128), ('Tristeza', FALSE, 128), ('Dolor', FALSE, 128),
('Natasha Romanoff', TRUE, 129), ('Yelena Belova', FALSE, 129), ('Melina Vostokoff', FALSE, 129), ('Dottie Underwood', FALSE, 129),
('Clint Barton', TRUE, 130), ('Kate Bishop', FALSE, 130), ('Trick Shot', FALSE, 130), ('Crossfire', FALSE, 130),
('Vengadores', TRUE, 131), ('Defensores', FALSE, 131), ('Cuatro Fantásticos', FALSE, 131), ('X-Men', FALSE, 131),
('Liga de la Justicia', TRUE, 132), ('Sociedad de la Justicia', FALSE, 132), ('Titanes', FALSE, 132), ('Doom Patrol', FALSE, 132),
('Logan', TRUE, 133), ('James Howlett', FALSE, 133), ('Weapon X', FALSE, 133), ('Patch', FALSE, 133),
('Factor de curación', TRUE, 134), ('Garras', FALSE, 134), ('Fuerza', FALSE, 134), ('Sentidos', FALSE, 134),
('Scott Summers', TRUE, 135), ('Alex Summers', FALSE, 135), ('Gabriel Summers', FALSE, 135), ('Nathan Summers', FALSE, 135),
('Rayos ópticos', TRUE, 136), ('Telepatía', FALSE, 136), ('Telequinesis', FALSE, 136), ('Fuerza', FALSE, 136),
('Ororo Munroe', TRUE, 137), ('Jean Grey', FALSE, 137), ('Rogue', FALSE, 137), ('Kitty Pryde', FALSE, 137),
('Control del clima', TRUE, 138), ('Telepatía', FALSE, 138), ('Vuelo', FALSE, 138), ('Fuerza', FALSE, 138),
('Charles Xavier', TRUE, 139), ('Erik Lehnsherr', FALSE, 139), ('Logan', FALSE, 139), ('Scott Summers', FALSE, 139),
('Charles Francis Xavier', TRUE, 140), ('Charles Montgomery Xavier', FALSE, 140), ('Charles Edward Xavier', FALSE, 140), ('Charles William Xavier', FALSE, 140),
('Magneto', TRUE, 141), ('Apocalipsis', FALSE, 141), ('Siniestro', FALSE, 141), ('Centinelas', FALSE, 141),
('Erik Lehnsherr', TRUE, 142), ('Max Eisenhardt', FALSE, 142), ('Magnus', FALSE, 142), ('Erik Magnus', FALSE, 142),
('Wade Wilson', TRUE, 143), ('Jack Wilson', FALSE, 143), ('Ryan Wilson', FALSE, 143), ('Wade Williams', FALSE, 143),
('Rompe la cuarta pared', TRUE, 144), ('Inmortalidad', FALSE, 144), ('Teletransporte', FALSE, 144), ('Regeneración', FALSE, 144),
('Matt Murdock', TRUE, 145), ('Mike Murdock', FALSE, 145), ('Jack Murdock', FALSE, 145), ('Frank Murdock', FALSE, 145),
('Vista', TRUE, 146), ('Oído', FALSE, 146), ('Tacto', FALSE, 146), ('Olfato', FALSE, 146),
('Frank Castle', TRUE, 147), ('Frank Castiglione', FALSE, 147), ('Frank Rook', FALSE, 147), ('Frank Costa', FALSE, 147),
('Muerte de su familia', TRUE, 148), ('Traición militar', FALSE, 148), ('Experimento fallido', FALSE, 148), ('Accidente', FALSE, 148),
('Stephen Strange', TRUE, 149), ('Victor Strange', FALSE, 149), ('Vincent Strange', FALSE, 149), ('Stewart Strange', FALSE, 149),
('Magia', TRUE, 150), ('Medicina', FALSE, 150), ('Ciencia', FALSE, 150), ('Tecnología', FALSE, 150);

-- Preguntas nivel difícil
INSERT INTO pregunta (enunciado, dificultad, pista, explicacion, id_categoria) VALUES
('¿En qué año fue creado Superman por Jerry Siegel y Joe Shuster?', 'divina', 'Década de los 30 del siglo XX.', 'Superman apareció por primera vez en Action Comics #1 en 1938.', 2),
('¿Cuál es el nombre kryptoniano de Superman?', 'divina', 'Su nombre de nacimiento en Krypton.', 'Kal-El es su verdadero nombre kryptoniano.', 2),
('¿Cómo se llama el padre biológico de Superman?', 'divina', 'Científico de Krypton que lo envió a la Tierra.', 'Jor-El salvó a su hijo del destino de Krypton.', 2),
('¿Cuál es el nombre de la fortaleza secreta de Superman?', 'divina', 'Refugio en el Ártico hecho de cristales.', 'La Fortaleza de la Soledad es su santuario.', 2),
('¿Qué significa la "S" en el pecho de Superman?', 'divina', 'No es una letra del alfabeto terrestre.', 'Es el símbolo kryptoniano de la esperanza.', 2),
('¿Cuál es el nombre real del primer Robin?', 'divina', 'Acróbata huérfano del circo.', 'Dick Grayson fue el primer compañero de Batman.', 2),
('¿Cómo se llama la cárcel psiquiátrica de Gotham?', 'divina', 'Donde encierran a los villanos locos.', 'Arkham Asylum alberga a los criminales dementes.', 2),
('¿Cuál es el nombre del comisionado de policía aliado de Batman?', 'divina', 'Padre de Batgirl en algunas versiones.', 'James Gordon es el aliado más leal de Batman.', 2),
('¿Qué empresa dirige Bruce Wayne?', 'divina', 'Corporación multimillonaria de Gotham.', 'Wayne Enterprises financia las actividades de Batman.', 2),
('¿Cuál es el nombre del tío de Spider-Man?', 'divina', 'Su muerte motivó a Peter a ser héroe.', 'Ben Parker le enseñó que "un gran poder conlleva una gran responsabilidad".', 2),
('¿Cómo se llama la tía de Spider-Man?', 'divina', 'Cuidó de Peter tras la muerte de sus padres.', 'May Parker es la figura materna de Peter.', 2),
('¿Cuál es el nombre del periódico donde trabaja Peter Parker?', 'divina', 'Diario sensacionalista de Nueva York.', 'El Daily Bugle publica fotos de Spider-Man.', 2),
('¿Cómo se llama el jefe de Peter Parker en el periódico?', 'divina', 'Editor que odia a Spider-Man.', 'J. Jonah Jameson considera a Spider-Man una amenaza.', 2),
('¿Cuál es el nombre de la madre de Wonder Woman?', 'divina', 'Reina de las Amazonas.', 'Hipólita gobierna Themyscira y es madre de Diana.', 2),
('¿Quién creó a Wonder Woman en los cómics?', 'divina', 'Psicólogo que inventó el detector de mentiras.', 'William Moulton Marston creó el personaje en 1941.', 2),
('¿Cuál es el nombre del dios que le dio poderes a Wonder Woman?', 'divina', 'Mensajero de los dioses griegos.', 'Hermes le otorgó velocidad y capacidad de vuelo.', 2),
('¿Cómo se llama la ciudad natal de Flash?', 'divina', 'Ciudad gemela de Keystone City.', 'Central City es el hogar de Barry Allen.', 2),
('¿Cuál es el nombre de la dimensión de donde obtiene velocidad Flash?', 'divina', 'Fuente extradimensional de energía.', 'La Speed Force es el origen de sus poderes.', 2),
('¿Quién fue el Flash original de los años 40?', 'divina', 'Miembro de la Sociedad de la Justicia.', 'Jay Garrick fue el primer Flash en los cómics.', 2),
('¿Cuál es el nombre del cuerpo de Green Lanterns?', 'divina', 'Organización intergaláctica de paz.', 'El Green Lantern Corps protege el universo.', 2),
('¿En qué planeta está la sede del Green Lantern Corps?', 'divina', 'Mundo artificial en el centro del universo.', 'Oa es el planeta hogar de los Guardianes.', 2),
('¿Cómo se llaman los creadores del Green Lantern Corps?', 'divina', 'Seres azules inmortales.', 'Los Guardianes del Universo fundaron el cuerpo.', 2),
('¿Cuál es el nombre del tridente de Aquaman?', 'divina', 'Arma mágica de los reyes de Atlantis.', 'El Tridente de Neptuno le da poder sobre los mares.', 2),
('¿Cómo se llama el medio hermano villano de Aquaman?', 'divina', 'Pretendiente al trono de Atlantis.', 'Ocean Master es uno de sus enemigos recurrentes.', 2),
('¿Cuál es el nombre real de Ocean Master?', 'divina', 'Hermano celoso del rey de Atlantis.', 'Orm Marius es la identidad de Ocean Master.', 2),
('¿Cómo se llama la inteligencia artificial de Iron Man?', 'divina', 'Asistente virtual del traje.', 'FRIDAY reemplazó a JARVIS en algunas versiones.', 2),
('¿Cuál era el nombre de la IA anterior de Tony Stark?', 'divina', 'Mayordomo virtual basado en Alfred.', 'JARVIS fue la primera IA de Iron Man.', 2),
('¿Cómo se llama la empresa de Tony Stark?', 'divina', 'Corporación de tecnología avanzada.', 'Stark Industries desarrolla tecnología militar.', 2),
('¿Cuál es el nombre del suero que creó a Captain America?', 'divina', 'Fórmula militar experimental.', 'El Suero del Súper Soldado transformó a Steve Rogers.', 2),
('¿Quién creó el suero del súper soldado?', 'divina', 'Científico alemán refugiado.', 'Abraham Erskine desarrolló la fórmula secreta.', 2),
('¿Cuál es el nombre del reino de Thor?', 'divina', 'Uno de los nueve mundos nórdicos.', 'Asgard es el hogar de los dioses nórdicos.', 2),
('¿Cómo se llama el padre de Thor?', 'divina', 'Rey de Asgard y padre de todos.', 'Odín es el Padre de Todo en la mitología nórdica.', 2),
('¿Cuál es el nombre del hermano adoptivo de Thor?', 'divina', 'Dios de las mentiras y el engaño.', 'Loki es el hermano problemático de Thor.', 2),
('¿Cómo se llama el puente que conecta los nueve mundos?', 'divina', 'Puente arcoíris de la mitología nórdica.', 'Bifrost conecta Asgard con otros reinos.', 2),
('¿Cuál es el nombre del científico que creó a Hulk?', 'divina', 'Trabajaba en la bomba gamma.', 'Bruce Banner se expuso accidentalmente a radiación gamma.', 2),
('¿Cómo se llama la prima de Bruce Banner?', 'divina', 'Abogada que también se volvió verde.', 'Jennifer Walters se convirtió en She-Hulk.', 2),
('¿Cuál es el nombre de la organización de espías de Marvel?', 'divina', 'Agencia internacional de seguridad.', 'S.H.I.E.L.D. protege el mundo de amenazas.', 2),
('¿Quién es el director de S.H.I.E.L.D. más famoso?', 'divina', 'Veterano de guerra con parche en el ojo.', 'Nick Fury dirigió la organización durante décadas.', 2),
('¿Cuál es el nombre real de la Viuda Negra original?', 'divina', 'Espía rusa entrenada en la Habitación Roja.', 'Natasha Romanoff es su identidad occidental.', 2),
('¿Cómo se llama el programa que entrenó a Black Widow?', 'divina', 'Programa soviético de espías.', 'La Habitación Roja creó asesinas perfectas.', 2),
('¿Cuál es el nombre del metal que cubre el esqueleto de Wolverine?', 'divina', 'Metal indestructible creado artificialmente.', 'El adamantium fue fusionado con sus huesos.', 2),
('¿Cómo se llama el programa que experimentó con Wolverine?', 'divina', 'Proyecto militar canadiense secreto.', 'Weapon X creó soldados mutantes mejorados.', 2),
('¿Cuál es el nombre de la escuela de los X-Men?', 'divina', 'Instituto para jóvenes superdotados.', 'La Escuela Xavier para Jóvenes Superdotados.', 2),
('¿En qué estado está ubicada la mansión X?', 'divina', 'Estado del noreste de Estados Unidos.', 'Westchester, Nueva York alberga la escuela.', 2),
('¿Cuál es el nombre real de Jean Grey?', 'divina', 'Telepática que se convirtió en Fénix.', 'Jean Grey-Summers es su nombre completo.', 2),
('¿Cómo se llama la entidad cósmica que poseyó a Jean Grey?', 'divina', 'Fuerza primordial de vida y muerte.', 'La Fuerza Fénix es una entidad cósmica.', 2),
('¿Cuál es el nombre del metal del escudo de Captain America?', 'divina', 'Metal ficticio más resistente que existe.', 'El vibranium absorbe vibraciones y energía.', 2),
('¿De qué país africano proviene el vibranium?', 'divina', 'Nación tecnológicamente avanzada.', 'Wakanda es la fuente principal de vibranium.', 2),
('¿Cuál es el nombre del rey de Wakanda?', 'divina', 'Superhéroe protector de su nación.', 'TChalla es el Black Panther y rey.', 2),
('¿Cómo se llama la hermana genio de TChalla?', 'divina', 'Princesa e inventora de Wakanda.', 'Shuri es la hermana menor de Black Panther.', 2);

-- Respuestas nivel difícil
INSERT INTO respuesta (texto, es_correcta, id_pregunta) VALUES
('1938', TRUE, 151), ('1939', FALSE, 151), ('1940', FALSE, 151), ('1937', FALSE, 151),
('Kal-El', TRUE, 152), ('Jor-El', FALSE, 152), ('Zor-El', FALSE, 152), ('Kara-El', FALSE, 152),
('Jor-El', TRUE, 153), ('Zor-El', FALSE, 153), ('Kal-El', FALSE, 153), ('Lor-El', FALSE, 153),
('Fortaleza de la Soledad', TRUE, 154), ('Cueva de Cristal', FALSE, 154), ('Santuario Ártico', FALSE, 154), ('Refugio Polar', FALSE, 154),
('Esperanza', TRUE, 155), ('Fuerza', FALSE, 155), ('Justicia', FALSE, 155), ('Superman', FALSE, 155),
('Dick Grayson', TRUE, 156), ('Jason Todd', FALSE, 156), ('Tim Drake', FALSE, 156), ('Damian Wayne', FALSE, 156),
('Arkham Asylum', TRUE, 157), ('Blackgate', FALSE, 157), ('Belle Reve', FALSE, 157), ('Iron Heights', FALSE, 157),
('James Gordon', TRUE, 158), ('Harvey Bullock', FALSE, 158), ('Sarah Essen', FALSE, 158), ('Renee Montoya', FALSE, 158),
('Wayne Enterprises', TRUE, 159), ('Wayne Industries', FALSE, 159), ('Wayne Corp', FALSE, 159), ('Wayne Tech', FALSE, 159),
('Ben Parker', TRUE, 160), ('Richard Parker', FALSE, 160), ('Martin Parker', FALSE, 160), ('Henry Parker', FALSE, 160),
('May Parker', TRUE, 161), ('Anna Parker', FALSE, 161), ('Mary Parker', FALSE, 161), ('Helen Parker', FALSE, 161),
('Daily Bugle', TRUE, 162), ('Daily Globe', FALSE, 162), ('New York Times', FALSE, 162), ('Daily Planet', FALSE, 162),
('J. Jonah Jameson', TRUE, 163), ('Robbie Robertson', FALSE, 163), ('Ben Urich', FALSE, 163), ('Frederick Foswell', FALSE, 163),
('Hipólita', TRUE, 164), ('Antíope', FALSE, 164), ('Penthesilea', FALSE, 164), ('Artemisa', FALSE, 164),
('William Moulton Marston', TRUE, 165), ('Bob Kane', FALSE, 165), ('Jerry Siegel', FALSE, 165), ('Stan Lee', FALSE, 165),
('Hermes', TRUE, 166), ('Zeus', FALSE, 166), ('Ares', FALSE, 166), ('Apolo', FALSE, 166),
('Central City', TRUE, 167), ('Keystone City', FALSE, 167), ('Coast City', FALSE, 167), ('Star City', FALSE, 167),
('Speed Force', TRUE, 168), ('Time Force', FALSE, 168), ('Velocity Force', FALSE, 168), ('Kinetic Force', FALSE, 168),
('Jay Garrick', TRUE, 169), ('Barry Allen', FALSE, 169), ('Wally West', FALSE, 169), ('Bart Allen', FALSE, 169),
('Green Lantern Corps', TRUE, 170), ('Lantern Brigade', FALSE, 170), ('Emerald Knights', FALSE, 170), ('Guardian Force', FALSE, 170),
('Oa', TRUE, 171), ('Mogo', FALSE, 171), ('Korugar', FALSE, 171), ('Rann', FALSE, 171),
('Guardianes del Universo', TRUE, 172), ('Controladores', FALSE, 172), ('Zamarones', FALSE, 172), ('Manhunters', FALSE, 172),
('Tridente de Neptuno', TRUE, 173), ('Tridente de Poseidón', FALSE, 173), ('Lanza Marina', FALSE, 173), ('Cetro Oceánico', FALSE, 173),
('Ocean Master', TRUE, 174), ('Black Manta', FALSE, 174), ('King Shark', FALSE, 174), ('Killer Croc', FALSE, 174),
('Orm Marius', TRUE, 175), ('David Hyde', FALSE, 175), ('Stephen Shin', FALSE, 175), ('Nanaue', FALSE, 175),
('FRIDAY', TRUE, 176), ('JARVIS', FALSE, 176), ('KAREN', FALSE, 176), ('EDITH', FALSE, 176),
('JARVIS', TRUE, 177), ('FRIDAY', FALSE, 177), ('KAREN', FALSE, 177), ('EDITH', FALSE, 177),
('Stark Industries', TRUE, 178), ('Stark Enterprises', FALSE, 178), ('Stark Corporation', FALSE, 178), ('Stark Technologies', FALSE, 178),
('Suero del Súper Soldado', TRUE, 179), ('Fórmula Vita-Ray', FALSE, 179), ('Compuesto Erskine', FALSE, 179), ('Serum Alpha', FALSE, 179),
('Abraham Erskine', TRUE, 180), ('Howard Stark', FALSE, 180), ('Hank Pym', FALSE, 180), ('Bruce Banner', FALSE, 180),
('Asgard', TRUE, 181), ('Valhalla', FALSE, 181), ('Midgard', FALSE, 181), ('Jotunheim', FALSE, 181),
('Odín', TRUE, 182), ('Balder', FALSE, 182), ('Heimdall', FALSE, 182), ('Tyr', FALSE, 182),
('Loki', TRUE, 183), ('Balder', FALSE, 183), ('Heimdall', FALSE, 183), ('Hogun', FALSE, 183),
('Bifrost', TRUE, 184), ('Yggdrasil', FALSE, 184), ('Gjallarhorn', FALSE, 184), ('Gungnir', FALSE, 184),
('Bruce Banner', TRUE, 185), ('Robert Banner', FALSE, 185), ('David Banner', FALSE, 185), ('Brian Banner', FALSE, 185),
('Jennifer Walters', TRUE, 186), ('Betty Ross', FALSE, 186), ('Rebecca Banner', FALSE, 186), ('Susan Banner', FALSE, 186),
('S.H.I.E.L.D.', TRUE, 187), ('H.A.M.M.E.R.', FALSE, 187), ('A.I.M.', FALSE, 187), ('HYDRA', FALSE, 187),
('Nick Fury', TRUE, 188), ('Phil Coulson', FALSE, 188), ('Maria Hill', FALSE, 188), ('Dum Dum Dugan', FALSE, 188),
('Natasha Romanoff', TRUE, 189), ('Yelena Belova', FALSE, 189), ('Melina Vostokoff', FALSE, 189), ('Dottie Underwood', FALSE, 189),
('Habitación Roja', TRUE, 190), ('Programa Invierno', FALSE, 190), ('Proyecto Insight', FALSE, 190), ('Operación Paperclip', FALSE, 190),
('Adamantium', TRUE, 191), ('Vibranium', FALSE, 191), ('Unobtainium', FALSE, 191), ('Carbonadium', FALSE, 191),
('Weapon X', TRUE, 192), ('Weapon Plus', FALSE, 192), ('Proyecto Rebirth', FALSE, 192), ('Experimento X', FALSE, 192),
('Escuela Xavier', TRUE, 193), ('Instituto Mutante', FALSE, 193), ('Academia X', FALSE, 193), ('Escuela Gifted', FALSE, 193),
('Nueva York', TRUE, 194), ('Massachusetts', FALSE, 194), ('Connecticut', FALSE, 194), ('Nueva Jersey', FALSE, 194),
('Jean Grey', TRUE, 195), ('Jean Summers', FALSE, 195), ('Marvel Girl', FALSE, 195), ('Phoenix', FALSE, 195),
('Fuerza Fénix', TRUE, 196), ('Entidad Cósmica', FALSE, 196), ('Poder Fénix', FALSE, 196), ('Espíritu Fénix', FALSE, 196),
('Vibranium', TRUE, 197), ('Adamantium', FALSE, 197), ('Unobtainium', FALSE, 197), ('Proto-Adamantium', FALSE, 197),
('Wakanda', TRUE, 198), ('Genosha', FALSE, 198), ('Latveria', FALSE, 198), ('Atlantis', FALSE, 198),
('TChalla', TRUE, 199), ('TChaka', FALSE, 199), ('MBaku', FALSE, 199), ('WKabi', FALSE, 199),
('Shuri', TRUE, 200), ('Nakia', FALSE, 200), ('Okoye', FALSE, 200), ('Ramonda', FALSE, 200);